### ISSUE TITLE
Questions on HashTable

### ISSUE THREAD

**Issue by twoflypig** [NVIDIA/HugeCTR#11]
Hi, thanks for the nice work. I viewed the code and meet the following quesitons. 
1. Where is the **hash map** palced? 
The **hash map** is responsible for mapping the input to a value. For example, given the input 10 and the bucket size 100, so it's hash value is 
```python
822 = hash('10')%100
```
But what I can find is only hasbTable to store the mapping <10, 822>. I want to know the part it generates the 822.

2. Does the embedding table support dynamic growth?
I see the embedding table behind the hashtable is a fixed size. [ses here](https://github.com/NVIDIA/HugeCTR/blob/ba76e902259ec8d4f28558fde0de52f1eea46e31/HugeCTR/include/embeddings/localized_slot_sparse_embedding_hash.hpp#L300). So the **HashTable is dynamic** but **the embedding table is fixed**?

**Comment by HWZealot** [comment]
Hi,
The hash function in the hash table map the input key to a bucket in the hash table. Then, the <key, index> pair is stored in that bucket. The index in the <key, index> pair is the index to a position in another linear array that actually store the value that maps to the key. 
Both the hash table and the array that stores the value is in GPU memory.

**Comment by twoflypig** [comment]
Thanks for your reply. The answer solves the first question. How about **second** question?

**Comment by wl1136** [comment]
Hi @twoflypig ,
Both HashTable and EmbeddingTable has a "size" which presents the max number of keys/values can be stored/loaded on GPU. For HashTable, you treat it as dynamic since you think the hash table is empty at the beginning and can be inserted by new <key, value> pairs. In our design, the "value" in HashTable is the row index in EmbeddingTable (we can call it value_index), and it increases linearly and is equal to the total number of <key,value> pairs in HashTable. So, the EmbeddingTable is also dynamic, and the number of embedding vectors in EmbeddingTable increases according to the number of <key, value> pairs in HashTable.

**Comment by twoflypig** [comment]
@wl1136 @HWZealot Thanks for the answers. Now I find another problem about max_nnz( **the size of slot**). 
As the User Guid said, max_nnz controls the max length of slot. -1 means invalid index and will be filled with zeros. So I have the following two questions:
1. What I can find about the implements of -1 is in the [readme.md of the demo](https://github.com/NVIDIA/HugeCTR/blob/master/tutorial/dump_to_tf/readMe.md). Is it the same in the **training period** ?  If I set max_nnz to be 3 but actually the gold max_nzz is 1,  the batch will be [[1, -1, -1], [10,-1,-1]] in the **training period**? I'm not familiar with c++ code in HugeCTR/include/embeddings. 
2. Is max_nnz will pad all slots to the length max_nnz, including the slot belongs to  one-hot categorical features? 
Great thanks to your kind reply！

**Comment by HWZealot** [comment]
Hi @twoflypig , 
Yes, your understanding is right. The feature index between row_offset[i] and row_offset[i+1] will be regarded as the features in the same slot. And nnz is also calculated by row_offset[i+1] - row_offset[i].

**Comment by twoflypig** [comment]
Thanks for the reply. That solved my question!
