### ISSUE TITLE
Perf benchmark on A100? 

### ISSUE THREAD

**Issue by eric-haibin-lin** [NVIDIA/HugeCTR#14]
Is there any performance benchmark result for the latest HugeCTR release on A100 GPUs? https://github.com/NVIDIA/HugeCTR/releases/tag/v2.1_a100_update

**Comment by zehuanw** [comment]
Thank you for your attention! We will release benchmark soon.

**Comment by HWZealot** [comment]
@eric-haibin-lin The latest HugeCTR release has participated in MLPerf Training v0.7 benchmark, the result can be found here: https://mlperf.org/training-results-0-7
