### ISSUE TITLE
Custom models on HugeCTR

### ISSUE THREAD

**Issue by quocdat32461997** [NVIDIA/HugeCTR#18]
Hi HugeCTR experts, 

I want to implement a custom model on HugeCTR. So far, I could not find docs that show how to import layers/optimizers to build a custom model. Or is there anything I miss?

I wonder if you guys have or will release documentations that show how to build custom model?

Thanks

**Comment by BookChan** [comment]
You can custom your model by writing json config file ,which describes your model structure. You can see the samples here:  https://github.com/NVIDIA/HugeCTR/tree/master/samples .  And also you can find the layer description in here:https://github.com/NVIDIA/HugeCTR/blob/master/docs/hugectr_user_guide.md .  

By the way you can only design your model that  can be  composed  by the  hugectr layers :
# AddLayer
 * Layer which does element-wise add by input tensors.
 * All the input tensors should have the same shape.
 
# BatchNormLayer
 * BatchNorm layer based on cuDNN

# ConcatLayer
 * Layer which merges the multiple 2D input tensors to a single 2D output tensor.
 * The input tensors and the resulting output tensor must have the same dimensionallity.
 * Only the innermost dimension is expanded by concatenating those of the input tensors.

# DropoutLayer
* Dropout layer which selects an arbitrary fraction of inputs to 0
* fraction of the inputs set to zero., 0 < rate < 1, default = 0.5

 
# EluLayer
Elu activation function as a derived class of Layer

# FmOrder2Layer

# FullyConnectedLayer

# MultiCrossLayer

# MultiplyLayer

# ReduceSumLayer

# ReluLayer

# ReshapeLayer

# SliceLayer

**Comment by zehuanw** [comment]
Thank you for your question. The same requirement will be tracked in #19. Mark as duplicate. Please let me know if they are different requirements.

**Comment by quocdat32461997** [comment]
Thanks. After looking in details the docs, it's clearer. I will close this issue.
