### ISSUE TITLE
[Question] Inference with HugeCTR 2.3

### ISSUE THREAD

**Issue by ashutoshk0** [NVIDIA/HugeCTR#205]
Regarding the inference support with HugeCTR, the inference module is not available in HugeCTR 2.3. (It is there in the 3.0 version as appears from the tutorials on github but the NGC catalog still shows the previous version i.e, 2.3). Is there any alternative way to do the same with the existing version?

**Comment by zehuanw** [comment]
Hi @ashutoshk0 , our new container will ship with v3.0 Release on 1st March. We will update the link of it soon. THX!
