### ISSUE TITLE
[Question]"current batchsize" vs "batchsize", what's the difference?

### ISSUE THREAD

**Issue by initzhang** [NVIDIA/HugeCTR#206]
Sometimes when I ran hugectr, some "current_batchsize" infos are printed out like:

```
...
[5894.42, train_epoch_start, 0, ]
[23d11h52m41s][HUGECTR][INFO]: Iter: 200 Time(200 iters): 12.129896s Loss: 0.541634 lr:0.335000
current_batchsize: 39624 batchsize: 65000
...
```

When I set the batchsize to 65536, the hugectr reported OOM-related errors and aborted, but when I set the batchsize to 65000 , the errors are gone and the "current_batchsize" appears. Does the "current_batchsize" mean that the batchsize is changed to 39624 during runtime implicitly? Is there a threshold between OOM and such auto-batchsize-reduction behavior?

**Comment by zehuanw** [comment]
> Does the "current_batchsize" mean that the batchsize is changed to 39624 during runtime implicitly?
Good question. In HugeCTR, to handle the last minibatch of dataset, we change the effective batchsize to `current_batchsize` in evaluation. E.g. the size of test set is 101 and the batchsize in evaluation is 10, then after 10 forward, the next forward will only have 1 effective sample. In this case, `current_batchsize` will show `1` temporarily.

**Comment by initzhang** [comment]
> Good question. In HugeCTR, to handle the last minibatch of dataset, we change the effective batchsize to `current_batchsize` in evaluation. E.g. the size of test set is 101 and the batchsize in evaluation is 10, then after 10 forward, the next forward will only have 1 effective sample. In this case, `current_batchsize` will show `1` temporarily.

Got it, Thanks!
