### ISSUE TITLE
[Question] Kernel dies while creating Parameter server for HugeCTR Inference

### ISSUE THREAD

**Issue by ashutoshk0** [NVIDIA/HugeCTR#210]
I followed this [hugectr inference notebook](https://github.com/NVIDIA/HugeCTR/blob/master/notebooks/hugectr_inference.ipynb) to create an inference code with DLRM config file. Now, every time I am trying to create the parameter server object, kernel dies without any exception. 

`parameter_server= CreateParameterServer(['./config_files/dlrm_inference.json'], ['DLRM'], False)`

I am attaching the `dlrm_inference.json `file for reference

```
{
    "inference": {
    "max_batchsize": 1024,
    "dense_model_file": "./hugeCTR_saved_model_DLRM/_dense_18000.model",
    "sparse_model_file": "./hugeCTR_saved_model_DLRM/0_sparse_18000.model"
  },

    "layers": [ 
          {
          "name": "data",
          "type": "Data",
          "slot_size_array": [49865, 54893, 337691, 9523, 164],
          "slot_size_array_orig": [49865, 54893, 337691, 9523, 164],
          "source": "./hugeCTR/filelist.txt",
          "eval_source":"./hugeCTR/valid_filelist.txt",
          "check": "None",
          "cache_eval_data": true,
          "label": {
                  "top": "label",
                  "label_dim": 1
          },
          "dense": {
                  "top": "dense",
                  "dense_dim": 2
          },
          "sparse": [
                  {
              "top": "data1",
              "type": "LocalizedSlot",
              "max_feature_num_per_sample": 5,
              "max_nnz": 1,
              "slot_num": 5
                  }
          ]
        },

        {
          "name": "sparse_embedding1",
          "type": "LocalizedSlotSparseEmbeddingHash",
          "bottom": "data1",
          "top": "sparse_embedding1",
          "sparse_embedding_hparam": {
            "slot_size_array": [49865, 54893, 337691, 9523, 164],
            "embedding_vec_size": 64,
            "combiner": 0
          }
        },

        {
          "name": "fc1",
          "type": "FusedInnerProduct",
          "bottom": "dense",
          "top": "fc1",
          "fc_param": {
            "num_output": 64
          }
        },

        {
          "name": "fc2",
          "type": "FusedInnerProduct",
          "bottom": "fc1",
          "top": "fc2",
          "fc_param": {
            "num_output": 128
          }
        },


        {
          "name": "fc3",
          "type": "FusedInnerProduct",
          "bottom": "fc2",
          "top": "fc3",
          "fc_param": {
            "num_output": 64
          }
        },

        {
          "name": "interaction1",
          "type": "Interaction",
          "bottom": ["fc3", "sparse_embedding1"],
          "top": "interaction1"
        },

        {
          "name": "fc4",
          "type": "FusedInnerProduct",
          "bottom": "interaction1",
          "top": "fc4",
           "fc_param": {
            "num_output": 1024
          }
        },

        {
          "name": "fc5",
          "type": "FusedInnerProduct",
          "bottom": "fc4",
          "top": "fc5",
          "fc_param": {
            "num_output": 1024
          }
        },

        {
          "name": "fc6",
          "type": "FusedInnerProduct",
          "bottom": "fc5",
          "top": "fc6",
          "fc_param": {
            "num_output": 512
          }
        },

        {
          "name": "fc7",
          "type": "FusedInnerProduct",
          "bottom": "fc6",
          "top": "fc7",
          "fc_param": {
            "num_output": 256
          }
        },

        {
          "name": "fc8",
          "type": "InnerProduct",
          "bottom": "fc7",
          "top": "fc8",
          "fc_param": {
            "num_output": 1
          }
        },
        
        {
          "name": "sigmoid",
          "type": "Sigmoid",
          "bottom": "fc8",
          "top": "sigmoid"
        }
    ]   
}

```

**Comment by yingcanw** [comment]
From your dlrm_inference.json config file, it seems that you are training DLRN with your own data set. The DLRM trained in the sample notebook uses the normal format with embedding key format as I32, so if your model is trained in parquet format or enable i64_input_key =true , then format embedding key is i64, you should enable I64 parameter server with
 `parameter_server= CreateParameterServer(['./config_files/dlrm_inference.json'], ['DLRM'], True)`

**Comment by ashutoshk0** [comment]
So, I ran it with I64 parameter server as True. I have trained the DRLM model with Norm dataset format following what was shown in the [movie lens notebook](https://github.com/NVIDIA/HugeCTR/blob/master/notebooks/movie-lens-example.ipynb). 

I got the following error: 
`*** The MPI_Comm_rank() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[51ddcc4e8547:00305] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
`

**Comment by yingcanw** [comment]
HugeCTR Inference does not enable MPI. Could you please try to use Inference docker from NGC. `nvcr.io/nvidia/merlin/merlin-inference:0.5`

**Comment by ashutoshk0** [comment]
> is the MPI error reported during the training or inference ? 

It was reported during Inference. I imported MPI and that issue was solved. 

>Is this one nvcr.io/nvidia/merlin/merlin-training:0.4 ?

Yes

**Comment by yingcanw** [comment]
Thanks for your feedback. We have updated the latest HugeCTR Python API code and instruction in each sample. You could  use `nvcr.io/nvidia/merlin/merlin-training:0.5` and  activate the merlin conda environment by running 
`source activate merlin`
So I can understand issue has been solved？

**Comment by ashutoshk0** [comment]
I tried with the updated `nvcr.io/nvidia/merlin/merlin-training:0.5` version. Again, I tried using with both supported argument types for the predict method-  `hugectr.inference.InferenceSession, dense_feature: List[float], embeddingcolumns: List[int], row_ptrs: List[int], i64_input_key: bool)` and `(self: hugectr.inference.InferenceSession, dense_feature: List[float], embeddingcolumns: List[int], row_ptrs: List[int]) -> List[float]`. 

I guess it keeps on printing the predicted values. How to solve this? I am attching the python script i am using for inference. Sorry for late follow-up. 

```
[22d10h49m18s][HUGECTR][INFO]: default_emb_vec_value is not specified using default: 0.000000
[22d10h49m19s][HUGECTR][INFO]: Global seed is 986885782
[22d10h49m21s][HUGECTR][INFO]: Peer-to-peer access cannot be fully enabled.
[22d10h49m21s][HUGECTR][INFO]: algorithm_search is not specified using default: 1
[22d10h49m21s][HUGECTR][INFO]: cuda_graph is not specified using default: 1
[22d10h49m21s][HUGECTR][INFO]: start create embedding for inference
[22d10h49m21s][HUGECTR][INFO]: sparse_input name data1
[22d10h49m21s][HUGECTR][INFO]: create embedding for inference success
Traceback (most recent call last):
  File "dlrm_inference.py", line 30, in <module>
    dlrm_inference(config_file, model_name, data_path)
  File "dlrm_inference.py", line 18, in dlrm_inference
    output = inference_session.predict(dense_features, embedding_columns, row_ptrs, False)
TypeError: predict(): incompatible function arguments. The following argument types are supported:
    1. (self: hugectr.inference.InferenceSession, dense_feature: List[float], embeddingcolumns: List[int], row_ptrs: List[int]) -> List[float]
    2. (self: hugectr.inference.InferenceSession, dense_feature: List[float], embeddingcolumns: List[int], row_ptrs: List[int], i64_input_key: bool) -> List[float]

Invoked with: <hugectr.inference.InferenceSession object at 0x7f638b3c48f0>, [0.001652892561983471, 0.7450980392156863, 0.0, 0.08888888888888889, 0.0, 0.0, 0.9583333333333331, 0.7450980392156863, 0.4791666666666666, 0.0007182188173330142, 0.0, 0.001652892561983471, 0.006222382541257103, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.001652892561983471, 0.6431372549019607, 0.04166666666666666, 0.11851851851851855, 0.0, 0.0, 0.9166666666666666, 0.6431372549019607, 0.4791666666666666, 0.0007182188173330142, 0.0, 0.001652892561983471, 0.006222382541257103, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.001652892561983471, 0.5764705882352941 ............(continued)

```

python script for inference:

```
import sys
from mpi4py import MPI
from sklearn.metrics import roc_auc_score
from hugectr.inference import CreateParameterServer, CreateEmbeddingCache, InferenceSession

def dlrm_inference(config_file, model_name, data_path):
      # read data from file
      data_file = open(data_path)
      labels = [int(item) for item in data_file.readline().split(' ')]
      dense_features = [float(item) for item in data_file.readline().split(' ')]
      embedding_columns = [int(item) for item in data_file.readline().split(' ')]
      row_ptrs = [int(item) for item in data_file.readline().split(' ')]
      # create parameter server, embedding cache and inference session
      parameter_server = CreateParameterServer([config_file], [model_name], False)
      embedding_cache = CreateEmbeddingCache(parameter_server, 0, True, 0.2, config_file, model_name, False)
      inference_session = InferenceSession(config_file, 0, embedding_cache)
      # make prediction and calculate accuracy
      output = inference_session.predict(dense_features, embedding_columns, row_ptrs, False)
      accuracy = calculate_accuracy(labels, output)
      print("[HUGECTR][INFO] prediction number samples: {}, accuracy: {}".format(len(labels), accuracy))

def calculate_accuracy(labels, output):
      score= roc_auc_score(labels, output)
      return score
    
if __name__ == "__main__":
      config_file = sys.argv[1]
      model_name = sys.argv[2]
      data_path = sys.argv[3]
      dlrm_inference(config_file, model_name, data_path)
```

**Comment by yingcanw** [comment]
I think this is because you did not use the complete criteo data(13 dense+26 categorical features) to train the dlrm model if you follow the [movie-lens-example.ipynb](https://github.com/NVIDIA/HugeCTR/blob/master/notebooks/movie-lens-example.ipynb) instructions.
 [hugectr_inference.ipynb](https://github.com/NVIDIA/HugeCTR/blob/master/notebooks/hugectr_inference.ipynb) uses the completed criteo data set to train the dcn model, and it is very important to use [criteo2predict.py](https://github.com/NVIDIA/HugeCTR/blob/master/tools/criteo_predict/criteo2predict.py) script to convert the preprocessed data to CSR format (for inference), you need to convert the your customized input data to csr format for inference , please refer to [CSR](https://github.com/triton-inference-server/hugectr_backend/blob/main/docs/architecture.md#vcsr-example) for details.

**Comment by yingcanw** [comment]
You can also refer to the **Prepare the inference session** part in [ecommerce-example.ipynb](https://github.com/NVIDIA/HugeCTR/blob/master/notebooks/ecommerce-example.ipynb), especially **Converting data to CSR format** step

**Comment by ashutoshk0** [comment]
I am working on a different dataset not the criteo one. I did follow the [criteo2predict.py](https://github.com/NVIDIA/HugeCTR/blob/master/tools/criteo_predict/criteo2predict.py) script before running the inference. Will go through the CSR documentation and try to resolve the problem i am facing. Thanks for the help!
