### ISSUE TITLE
[BUG] Kernel dies when call hugectr.model()

### ISSUE THREAD

**Issue by TruongThuyLiem** [NVIDIA/HugeCTR#222]
Hi all, I tied to run this code 

solver = hugectr.solver_parser_helper(num_epochs = 1,
                                    max_iter = 10000,
                                    max_eval_batches = 100,
                                    batchsize_eval = 2720,
                                    batchsize = 2720,
                                    display = 1000,
                                    eval_interval = 3200,
                                    i64_input_key = True,
                                    use_mixed_precision = False,
                                    repeat_dataset = True)
optimizer = hugectr.optimizer.CreateOptimizer(optimizer_type = hugectr.Optimizer_t.SGD,
                                    use_mixed_precision = False)
model = hugectr.Model(solver, optimizer)

when run 'model = hugectr.Model(solver, optimizer)', kernel dies without any notice.
What am I wrong? Please help me

**Comment by zehuanw** [comment]
Thank you for your feedback! Could you please also paste your full log and also the full instructions (network construction or json configure file)?

**Comment by kaustubhKVS** [comment]
Hey !! What helped me for faster error resolution was using a python file (.py) file for hugeCTR training.
I don't know why but hugeCTR doesn't give errors in ipynb notebooks, instead of throwing errors on screen the ipynb kernel dies.

Here are the steps which helped me :
1. Make a .py file for your hugeCTR training with all the required libraries.
2. Execute the file, 
e.g. python3  training.py
now in the terminal, you will see errors and other issues which the API runs into.

You can resolve those errors and then once you get a successful test run, shift to using jupyter notebook for error resolution.

**Comment by TruongThuyLiem** [comment]
> Thank you for your feedback! Could you please also paste your full log and also the full instructions (network construction or json configure file)?

I just run this code 
import hugectr
solver = hugectr.solver_parser_helper(num_epochs = 0,
                                    max_iter = 10000,
                                    max_eval_batches = 100,
                                    batchsize_eval = 2720,
                                    batchsize = 2720,
                                    display = 1000,
                                    eval_interval = 3200,
                                    i64_input_key = True,
                                    use_mixed_precision = False,
                                    repeat_dataset = True)
optimizer = hugectr.optimizer.CreateOptimizer(optimizer_type = hugectr.Optimizer_t.SGD,
                                    use_mixed_precision = False)
model = hugectr.Model(solver, optimizer)

and my issue just die kernel without any error showed 
![Screenshot from 2021-06-08 14-20-42](https://user-images.githubusercontent.com/18700207/121141635-6794f700-c865-11eb-9794-e0de18fd714a.png)

My code just create a model and I have not defined the network yet 
![Screenshot from 2021-06-08 14-21-07](https://user-images.githubusercontent.com/18700207/121141819-96ab6880-c865-11eb-9f78-aeb0caf93a84.png)

**Comment by TruongThuyLiem** [comment]
> Hey !! What helped me for faster error resolution was using a python file (.py) file for hugeCTR training.
> I don't know why but hugeCTR doesn't give errors in ipynb notebooks, instead of throwing errors on screen the ipynb kernel dies.
> 
> Here are the steps which helped me :
> 
> 1. Make a .py file for your hugeCTR training with all the required libraries.
> 2. Execute the file,
>    e.g. python3  training.py
>    now in the terminal, you will see errors and other issues which the API runs into.
> 
> You can resolve those errors and then once you get a successful test run, shift to using jupyter notebook for error resolution.

When I run my code in file.py on terminal, the error is
"===================================Model Init====================================
*** The MPI_Comm_size() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[8cec3e10985a:00325] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
"
Thank you

**Comment by zehuanw** [comment]
> > Hey !! What helped me for faster error resolution was using a python file (.py) file for hugeCTR training.
> > I don't know why but hugeCTR doesn't give errors in ipynb notebooks, instead of throwing errors on screen the ipynb kernel dies.
> > Here are the steps which helped me :
> > 
> > 1. Make a .py file for your hugeCTR training with all the required libraries.
> > 2. Execute the file,
> >    e.g. python3  training.py
> >    now in the terminal, you will see errors and other issues which the API runs into.
> > 
> > You can resolve those errors and then once you get a successful test run, shift to using jupyter notebook for error resolution.
> 
> When I run my code in file.py on terminal, the error is
> "===================================Model Init====================================
> *** The MPI_Comm_size() function was called before MPI_INIT was invoked.
> *** This is disallowed by the MPI standard.
> *** Your MPI job will now abort.
> [8cec3e10985a:00325] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
> "
> Thank you so much, I can see the error now



Could you please try to add `from mpi4py import MPI` in front of everything? Thanks!

**Comment by TruongThuyLiem** [comment]
> > > Hey !! What helped me for faster error resolution was using a python file (.py) file for hugeCTR training.
> > > I don't know why but hugeCTR doesn't give errors in ipynb notebooks, instead of throwing errors on screen the ipynb kernel dies.
> > > Here are the steps which helped me :
> > > 
> > > 1. Make a .py file for your hugeCTR training with all the required libraries.
> > > 2. Execute the file,
> > >    e.g. python3  training.py
> > >    now in the terminal, you will see errors and other issues which the API runs into.
> > > 
> > > You can resolve those errors and then once you get a successful test run, shift to using jupyter notebook for error resolution.
> > 
> > 
> > When I run my code in file.py on terminal, the error is
> > "===================================Model Init====================================
> > *** The MPI_Comm_size() function was called before MPI_INIT was invoked.
> > *** This is disallowed by the MPI standard.
> > *** Your MPI job will now abort.
> > [8cec3e10985a:00325] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
> > "
> > Thank you so much, I can see the error now
> 
> Could you please try to add `from mpi4py import MPI` in front of everything? Thanks!

It works 
Thank you so much

**Comment by kaustubhKVS** [comment]
> Hey !! What helped me for faster error resolution was using a python file (.py) file for hugeCTR training.
> I don't know why but hugeCTR doesn't give errors in ipynb notebooks, instead of throwing errors on screen the ipynb kernel dies.
> 
> Here are the steps which helped me :
> 
> 1. Make a .py file for your hugeCTR training with all the required libraries.
> 2. Execute the file,
>    e.g. python3  training.py
>    now in the terminal, you will see errors and other issues which the API runs into.
> 
> You can resolve those errors and then once you get a successful test run, shift to using jupyter notebook for error resolution.

> > Hey !! What helped me for faster error resolution was using a python file (.py) file for hugeCTR training.
> > I don't know why but hugeCTR doesn't give errors in ipynb notebooks, instead of throwing errors on screen the ipynb kernel dies.
> > Here are the steps which helped me :
> > 
> > 1. Make a .py file for your hugeCTR training with all the required libraries.
> > 2. Execute the file,
> >    e.g. python3  training.py
> >    now in the terminal, you will see errors and other issues which the API runs into.
> > 
> > You can resolve those errors and then once you get a successful test run, shift to using jupyter notebook for error resolution.
> 
> When I run my code in file.py on terminal, the error is
> "===================================Model Init====================================
> *** The MPI_Comm_size() function was called before MPI_INIT was invoked.
> *** This is disallowed by the MPI standard.
> *** Your MPI job will now abort.
> [8cec3e10985a:00325] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
> "
> Thank you so much, I can see the error now

@zehuanw  any idea why the interactive kernel dies ?? Like what is the reason for this, why does the kernel dies but the .py files give out specific errors ?? What exactly happens, just curious to know.

**Comment by zehuanw** [comment]
> Could you please try to add from mpi4py import MPI in front of everything? Thanks!

Hopes that the instruction above solve your problem too. If you built container with MPI enabled or Using NGC container, MPI api will be called in some of our instructions and it will require you to import mpi4py beforehand. Otherwise it will return such error.
