### ISSUE TITLE
[Question] does the "batchsize" refer to the total batchsize of all GPUs? 

### ISSUE THREAD

**Issue by initzhang** [NVIDIA/HugeCTR#223]
this question maybe silly but it does confuse me...

when I set the batchsize to 65536 with GPU [0,1,2,3],  does the actual batchsize for GPU0 equal to 16384? I infer this from the assertion in `/HugeCTR/HugeCTR/include/data_readers/data_reader.hpp:214`, namely `...|| 0 != batchsize_ % total_gpu_count ...`

**Comment by zehuanw** [comment]
Thank you for the question! Batchsize in configuration file or the arguments of python api means global batch size. So you are right here:

`when I set the batchsize to 65536 with GPU [0,1,2,3], does the actual batchsize for GPU0 equal to 16384?`

We will address your question in our user guide / python interface introduction.

**Comment by initzhang** [comment]
> Thank you for the question! Batchsize in configuration file or the arguments of python api means global batch size. So you are right here:
> 
> `when I set the batchsize to 65536 with GPU [0,1,2,3], does the actual batchsize for GPU0 equal to 16384?`
> 
> We will address your question in our user guide / python interface introduction.

got it, Thanks!
