### ISSUE TITLE
[Question] do we need file_list.keyset?

### ISSUE THREAD

**Issue by initzhang** [NVIDIA/HugeCTR#224]
The criteo2hugectr tool will generate files including: 
* file_list.keyset
* file_list.tmp
* file_list.txt
* embeddings/

I know that we need `embeddings` and `file_list.txt` because they appear in the json configuration file, but do we need to keep the file_list.keyset? or I can remove it safely just like file_list.tmp?

**Comment by XiaoleiShi-NV** [comment]
The `*.keyset` file is generated for the model oversubscription case (read [here](https://github.com/NVIDIA/HugeCTR/blob/master/docs/hugectr_user_guide.md#model-oversubscription) for the intro and sec 3.2 in [here](https://github.com/NVIDIA/HugeCTR/blob/master/notebooks/hugectr_criteo.ipynb) for sample). If you just want to train a model in the regular way, feel free to remove it.
