### ISSUE TITLE
[BUG][HCDEBUG][ERROR] Runtime error: Input size is not consistent! /var/tmp/HugeCTR/HugeCTR/pybind/inference_wrapper.hpp:121 

### ISSUE THREAD

**Issue by TruongThuyLiem** [NVIDIA/HugeCTR#225]
Hi everyone,
I tried to use  merlin-training version 0.5.3. After training a model by HugeCTR, I can not predict.
My label, dense, sparse in config file as below
![image](https://user-images.githubusercontent.com/18700207/124363164-e8c48b80-dc63-11eb-9d64-d5c01054411b.png)

That means a test sample has dense feature is 1 dim, category feature is 2 dim, so I tried to predict as below
![image](https://user-images.githubusercontent.com/18700207/124363143-c599dc00-dc63-11eb-988e-9a26566be98d.png)

I tried to a lot of different version merlin-training but it  doesn't work
Can someone help me?
Thank you so much

**Comment by KingsleyLiu-NV** [comment]
Could you please show the full content within `config_inference_file_path`?

**Comment by TruongThuyLiem** [comment]
> Could you please show the full content within `config_inference_file_path`?
This is my config_inference_file
inference = {
    "max_batchsize": 2048,
    "dense_model_file": "hugeCTR_saved_model_DLRM/_dense_30000.model",
    "sparse_model_file": "hugeCTR_saved_model_DLRM/0_sparse_30000.model",
    "input_key_type": 'I32' 
  }
layers = [ 
      {
      "name": "data",
      "type": "Data",
      "check": "None",
      "cache_eval_data": True,
      "label": {
              "top": "label",
              "label_dim": 1
      },
      "dense": {
              "top": "dense",
              "dense_dim": 1
      },
      "sparse": [
              {
          "top": "data1",
          "type": "LocalizedSlot",
          "max_feature_num_per_sample": 2,
          "max_nnz": 1,
          "slot_num": 2
              }
      ]
    },

    {
      "name": "sparse_embedding1",
      "type": "LocalizedSlotSparseEmbeddingHash",
      "bottom": "data1",
      "top": "sparse_embedding1",
      "sparse_embedding_hparam": {
        "slot_size_array": [1285908 , 233309],
        "embedding_vec_size": 64,
        "combiner": 0
      }
    },

    {
      "name": "fc1",
      "type": "InnerProduct",
      "bottom": "dense",
      "top": "fc1",
      "fc_param": {
        "num_output": 64
      }
    },

    {
      "name": "fc2",
      "type": "InnerProduct",
      "bottom": "fc1",
      "top": "fc2",
      "fc_param": {
        "num_output": 128
      }
    },

   
    {
      "name": "fc3",
      "type": "InnerProduct",
      "bottom": "fc2",
      "top": "fc3",
      "fc_param": {
        "num_output": 64
      }
    },

    {
      "name": "interaction1",
      "type": "Interaction",
      "bottom": ["fc3", "sparse_embedding1"],
      "top": "interaction1"
    },

    {
      "name": "fc4",
      "type": "InnerProduct",
      "bottom": "interaction1",
      "top": "fc4",
       "fc_param": {
        "num_output": 1024
      }
    },

    {
      "name": "fc5",
      "type": "InnerProduct",
      "bottom": "fc4",
      "top": "fc5",
      "fc_param": {
        "num_output": 1024
      }
    },

    {
      "name": "fc6",
      "type": "InnerProduct",
      "bottom": "fc5",
      "top": "fc6",
      "fc_param": {
        "num_output": 512
      }
    },

    {
      "name": "fc7",
      "type": "InnerProduct",
      "bottom": "fc6",
      "top": "fc7",
      "fc_param": {
        "num_output": 256
      }
    },

    {
      "name": "fc8",
      "type": "InnerProduct",
      "bottom": "fc7",
      "top": "fc8",
      "fc_param": {
        "num_output": 1
      }
    },
    
    {
      "name": "sigmoid",
      "type": "Sigmoid",
      "bottom": ["fc8"],
      "top": "sigmoid"
    } 
]

**Comment by KingsleyLiu-NV** [comment]
I see. Then could you please call the inference API like this (dropping `i64_input_key` argument):
`inference_session.predict(dense_feature=[1.0], embeddingcolumns=[342339,5], row_ptrs=[0,1,2])`

**Comment by TruongThuyLiem** [comment]
> I see. Then could you please call the inference API like this (dropping `i64_input_key` argument):
> `inference_session.predict(dense_feature=[1.0], embeddingcolumns=[342339,5], row_ptrs=[0,1,2])`

It works, thank you so much

**Comment by KingsleyLiu-NV** [comment]
Thanks for you feedback. Actually, we will the Python APIs a lot in the next release which can prevent users from misusing it in terms of the `i64_input_key` argument. Stay tuned.
