### ISSUE TITLE
Criteo dataset sample processing issue

### ISSUE THREAD

**Issue by TimJZ** [NVIDIA/HugeCTR#23]
I was trying to run HugeCTR on the Criteo Kaggle dataset. When I was converting the original Kaggle dataset to HugeCTR format using Criteo2hugeCTR_legacy tool, I was running the command line as following:

$ ./criteo2hugectr_legacy 1 ../../tools/criteo_script_legacy/train.out criteo/sparse_embedding file_list.txt
$ ./criteo2hugectr_legacy 1 ../../tools/criteo_script_legacy/test.out criteo_test/sparse_embedding file_list_test.txt

However, I'm not able to get the file_list.txt abd file_list_test.txt from these scripts. I'm not sure what I did wrong here, since I pretty much followed the readme online from the beginning.

I also did some trails and realized that the problem might be in criteo2hugectr_legacy.cpp, since I wasn't able to read the eof of txt_file (line 95). 

I'd really appreciate it if you guys could explain this a bit. Thank you very much!

**Comment by zehuanw** [comment]
Thank you for your feedback. 

Are you testing under our docker? I'm afraid there are some environment issues.

**Comment by msharmavikram** [comment]
@zehuanw It is a bit difficult to understand why this would be because of environmental issues. 

Taking a look at 
https://github.com/NVIDIA/HugeCTR/blob/master/tools/criteo_script_legacy/criteo2hugectr_legacy.cpp#L95 

The fundamental issue is `N` is smaller than the size of file and the end of file condition never gets triggered and hence file_list*.txt files never gets created. Isnt this a bug?

**Comment by JimShiTH** [comment]
I have tried serveal tests both on DGX-1 and my workstation, but I don't reproduce the problem. @TimJZ 

The `criteo_script_legacy` is used to translate the criteo dataset to hugectr format, and the input file `train.out` and `test.out` contains 36672493 and 4584062 lines respectively, and we set `N` to be 40960 in `criteo_script_legacy`, so it's not possible that "`N` is smaller than the size of file". @msharmavikram 

Please double check the whole process according to `samples/criteo/README.md` to see if there are any missed steps. Please feel free to post here if you find any problem. @TimJZ

**Comment by zehuanw** [comment]
Close as cannot reproduce and no reply for long time.
