### ISSUE TITLE
Error when run NCF model

### ISSUE THREAD

**Issue by taquanghung1705199** [NVIDIA/HugeCTR#230]
Iam running follow by the instruction of https://github.com/NVIDIA/HugeCTR/tree/master/samples/ncf#train-and-validate-the-ncf-model
but when I run **python ncf.py**, this error appear:
<pre>root@e9b5fab4b085:/hugectr# python ncf.py
Traceback (most recent call last):
  File &quot;ncf.py&quot;, line 3, in &lt;module&gt;
    solver = hugectr.CreateSolver(max_eval_batches = 100,
AttributeError: module &apos;hugectr&apos; has no attribute &apos;CreateSolver&apos;
</pre>
How to fix it ? Plz help me !

**Comment by zehuanw** [comment]
Hi @taquanghung1705199 , thank you for your feedback! It seems that you are using new version of HugeCTR under wrong container. What is the container you are using? We are going to release the container `merlin-training:0.6` for the current master branch and add release tag  this week.
