### ISSUE TITLE
Looks like missing dollar mark in dockerfile.

### ISSUE THREAD

**Issue by lazykyama** [NVIDIA/HugeCTR#27]
This is a trivial bug report.

It looks like the last argument at https://github.com/NVIDIA/HugeCTR/blob/master/tools/dockerfiles/build.Dockerfile#L36, `-DNCCL_A2A=NCCL_A2A`, should be replaced with `-DNCCL_A2A=$NCCL_A2A`.

**Comment by XiaoleiShi-NV** [comment]
Thank you, already corrected.

**Comment by lazykyama** [comment]
Thanks for the correcting this and sorry for late my response. I've confirmed this issue has been already resolved by PR #31.
