### ISSUE TITLE
hugeCTR train performance question

### ISSUE THREAD

**Issue by thewintersun** [NVIDIA/HugeCTR#9]
I watched Zehuan Wang's share "HugeCTR - 端到端点击率预估训练解决方案介绍", 
in this ppt, at the "PERFORMANCE" slide,  use the 8-GPU performance is only 17.8ms per iter. 
only 17.8ms per iter is too fast, Is this some error?

**Comment by zehuanw** [comment]
17.8ms is the real performance, please be free to benchmark directly on HugeCTR. We support benchmark tool here. 
https://github.com/NVIDIA/HugeCTR#benchmark
